In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

In [3]:
data = pd.read_excel("E:\project\AI_ML\Dataset_master.xlsx",sheet_name = "Covid_data_old" )
data

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\ysgup\AppData\Local\Temp\ipykernel_904\2160433306.py:1: SyntaxWarning: invalid escape sequence '\p'
  data = pd.read_excel("E:\project\AI_ML\Dataset_master.xlsx",sheet_name = "Covid_data_old" )

,age,body_temperature,chronic_disease,breathing_issue,Blood O2 Level in Percentage,Needed Hospitalization
0,10.0,Normal,no,no,97.0,No
1,12.0,Normal,no,no,97.0,No
2,15.0,Normal,no,no,94.0,No
3,10.0,Normal,no,no,97.0,No
4,13.0,Moderate,no,no,94.0,No
...,...,...,...,...,...,...
65,86.0,High,no,yes,76.0,Yes
66,61.0,Moderate,no,yes,90.0,No
67,94.0,High,yes,yes,64.0,Yes
68,81.0,High,yes,yes,75.0,Yes
69,76.0,High,yes,yes,80.0,Yes

In [5]:
# data = data.drop('Unnamed: 6',axis=1)

In [6]:
data

,age,body_temperature,chronic_disease,breathing_issue,Blood O2 Level in Percentage,Needed Hospitalization
0,10.0,Normal,no,no,97.0,No
1,12.0,Normal,no,no,97.0,No
2,15.0,Normal,no,no,94.0,No
3,10.0,Normal,no,no,97.0,No
4,13.0,Moderate,no,no,94.0,No
...,...,...,...,...,...,...
65,86.0,High,no,yes,76.0,Yes
66,61.0,Moderate,no,yes,90.0,No
67,94.0,High,yes,yes,64.0,Yes
68,81.0,High,yes,yes,75.0,Yes
69,76.0,High,yes,yes,80.0,Yes

In [7]:
X = data.drop('Needed Hospitalization', axis=1)
X

,age,body_temperature,chronic_disease,breathing_issue,Blood O2 Level in Percentage
0,10.0,Normal,no,no,97.0
1,12.0,Normal,no,no,97.0
2,15.0,Normal,no,no,94.0
3,10.0,Normal,no,no,97.0
4,13.0,Moderate,no,no,94.0
...,...,...,...,...,...
65,86.0,High,no,yes,76.0
66,61.0,Moderate,no,yes,90.0
67,94.0,High,yes,yes,64.0
68,81.0,High,yes,yes,75.0
69,76.0,High,yes,yes,80.0

In [8]:
y = data['Needed Hospitalization']
y

0      No
1      No
2      No
3      No
4      No
     ...
65    Yes
66     No
67    Yes
68    Yes
69    Yes
Name: Needed Hospitalization, Length: 70, dtype: object

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X.iloc[:,0:5:4])
X.iloc[:,0:5:4] = imputer.transform(X.iloc[:,0:5:4])

In [10]:
X

,age,body_temperature,chronic_disease,breathing_issue,Blood O2 Level in Percentage
0,10.0,Normal,no,no,97.0
1,12.0,Normal,no,no,97.0
2,15.0,Normal,no,no,94.0
3,10.0,Normal,no,no,97.0
4,13.0,Moderate,no,no,94.0
...,...,...,...,...,...
65,86.0,High,no,yes,76.0
66,61.0,Moderate,no,yes,90.0
67,94.0,High,yes,yes,64.0
68,81.0,High,yes,yes,75.0
69,76.0,High,yes,yes,80.0

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [15]:
X= pd.DataFrame(ct.fit_transform(X))

In [16]:
X

      0    1    2    3    4     5    6    7     8
0   1.0  0.0  1.0  0.0  1.0  10.0   no   no  97.0
1   1.0  0.0  1.0  0.0  1.0  12.0   no   no  97.0
2   1.0  0.0  1.0  0.0  1.0  15.0   no   no  94.0
3   1.0  0.0  1.0  0.0  1.0  10.0   no   no  97.0
4   0.0  1.0  0.0  0.0  0.0  13.0   no   no  94.0
..  ...  ...  ...  ...  ...   ...  ...  ...   ...
65  1.0  0.0  1.0  1.0  0.0  86.0   no  yes  76.0
66  0.0  1.0  0.0  0.0  0.0  61.0   no  yes  90.0
67  1.0  0.0  1.0  1.0  0.0  94.0  yes  yes  64.0
68  1.0  0.0  1.0  1.0  0.0  81.0  yes  yes  75.0
69  1.0  0.0  1.0  1.0  0.0  76.0  yes  yes  80.0

[70 rows x 9 columns]

In [14]:
pd.DataFrame(X)

      0    1    2    3     4    5    6     7
0   1.0  0.0  0.0  1.0  10.0   no   no  97.0
1   1.0  0.0  0.0  1.0  12.0   no   no  97.0
2   1.0  0.0  0.0  1.0  15.0   no   no  94.0
3   1.0  0.0  0.0  1.0  10.0   no   no  97.0
4   0.0  1.0  0.0  0.0  13.0   no   no  94.0
..  ...  ...  ...  ...   ...  ...  ...   ...
65  1.0  0.0  1.0  0.0  86.0   no  yes  76.0
66  0.0  1.0  0.0  0.0  61.0   no  yes  90.0
67  1.0  0.0  1.0  0.0  94.0  yes  yes  64.0
68  1.0  0.0  1.0  0.0  81.0  yes  yes  75.0
69  1.0  0.0  1.0  0.0  76.0  yes  yes  80.0

[70 rows x 8 columns]

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1])

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train

      0    1    2    3    4          5    6    7          8
62  1.0  0.0  1.0  1.0  0.0       86.0  yes  yes       71.0
30  0.0  1.0  0.0  0.0  0.0       35.0   no  yes       92.0
58  1.0  0.0  1.0  1.0  0.0       75.0   no  yes       72.0
35  1.0  0.0  1.0  1.0  0.0       42.0   no   no       92.0
57  1.0  0.0  1.0  1.0  0.0       74.0  yes  yes       75.0
47  1.0  0.0  1.0  1.0  0.0       62.0  yes  yes       68.0
16  0.0  1.0  0.0  0.0  0.0       24.0   no   no       92.0
34  0.0  1.0  0.0  0.0  0.0       48.0   no  yes       93.0
42  1.0  0.0  1.0  1.0  0.0       58.0   no   no       70.0
28  0.0  1.0  0.0  0.0  0.0  45.130435  yes   no       90.0
7   0.0  1.0  0.0  0.0  0.0       15.0   no   no       92.0
53  1.0  0.0  1.0  0.0  1.0       70.0   no  yes       88.0
40  1.0  0.0  1.0  1.0  0.0       52.0  yes  yes       80.0
44  1.0  0.0  1.0  1.0  0.0       60.0  yes  yes       68.0
46  1.0  0.0  1.0  1.0  0.0       54.0  yes  yes       70.0
19  1.0  0.0  1.0  0.0  1.0       29.0   no   no       93.0
56  1.0  0.0  1.0  1.0  0.0       78.0  yes  yes       71.0
39  1.0  0.0  1.0  1.0  0.0       36.0  yes   no       90.0
25  0.0  1.0  0.0  0.0  0.0       30.0  yes   no       86.0
38  1.0  0.0  1.0  1.0  0.0       50.0  yes  yes       77.0
13  1.0  0.0  1.0  0.0  1.0       18.0   no   no       93.0
50  1.0  0.0  1.0  1.0  0.0       69.0   no  yes       53.0
3   1.0  0.0  1.0  0.0  1.0       10.0   no   no       97.0
17  1.0  0.0  1.0  1.0  0.0       26.0   no   no       94.0
8   0.0  1.0  0.0  0.0  0.0       18.0   no   no       66.0
55  1.0  0.0  1.0  1.0  0.0       62.0  yes  yes       69.0
6   0.0  1.0  0.0  0.0  0.0       13.0   no   no       93.0
36  1.0  0.0  1.0  1.0  0.0       40.0   no   no       92.0
64  1.0  0.0  1.0  1.0  0.0       84.0  yes  yes       75.0
69  1.0  0.0  1.0  1.0  0.0       76.0  yes  yes       80.0
68  1.0  0.0  1.0  1.0  0.0       81.0  yes  yes       75.0
15  0.0  1.0  0.0  0.0  0.0       25.0   no   no       93.0
27  0.0  1.0  0.0  0.0  0.0       32.0   no  yes       84.0
41  1.0  0.0  1.0  1.0  0.0       56.0  yes  yes       77.0
26  0.0  1.0  0.0  0.0  0.0       35.0   no   no       89.0
48  1.0  0.0  1.0  1.0  0.0       63.0  yes  yes       66.0
24  1.0  0.0  1.0  0.0  1.0       28.0   no   no       89.0
59  1.0  0.0  1.0  1.0  0.0       56.0  yes   no       76.0
63  1.0  0.0  1.0  1.0  0.0       90.0  yes  yes       67.0
11  1.0  0.0  1.0  0.0  1.0       17.0   no   no       93.0
32  0.0  1.0  0.0  0.0  0.0       40.0   no  yes       90.0
66  0.0  1.0  0.0  0.0  0.0       61.0   no  yes       90.0
61  1.0  0.0  1.0  1.0  0.0       82.0  yes  yes       73.0
37  0.0  1.0  0.0  0.0  0.0       49.0   no   no       80.0
29  0.0  1.0  0.0  0.0  0.0       32.0   no   no       89.0
43  1.0  0.0  1.0  1.0  0.0       59.0   no  yes       69.0
65  1.0  0.0  1.0  1.0  0.0       86.0   no  yes       76.0
1   1.0  0.0  1.0  0.0  1.0       12.0   no   no       97.0
52  1.0  0.0  1.0  1.0  0.0       61.0  yes  yes       76.0
21  1.0  0.0  1.0  0.0  1.0       19.0   no   no       89.0
2   1.0  0.0  1.0  0.0  1.0       15.0   no   no       94.0
23  1.0  0.0  1.0  0.0  1.0       26.0   no   no  82.072464
20  0.0  1.0  0.0  0.0  0.0       30.0   no   no       62.0
60  1.0  0.0  1.0  1.0  0.0       80.0   no  yes       92.0
14  1.0  0.0  1.0  0.0  1.0       20.0   no   no       92.0
51  1.0  0.0  1.0  1.0  0.0       64.0  yes  yes       73.0

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train.iloc[:,8:] = sc.fit_transform(X_train.iloc[:,8:])
# X_train.iloc[:,5:] = sc.fit_transform(X_train.iloc[:,5:])
X_test.iloc[:,8:] = sc.fit_transform(X_test.iloc[:,8:])
X_train

      0    1    2    3    4          5    6    7         8
62  1.0  0.0  1.0  1.0  0.0       86.0  yes  yes -0.994186
30  0.0  1.0  0.0  0.0  0.0       35.0   no  yes  0.957435
58  1.0  0.0  1.0  1.0  0.0       75.0   no  yes -0.901252
35  1.0  0.0  1.0  1.0  0.0       42.0   no   no  0.957435
57  1.0  0.0  1.0  1.0  0.0       74.0  yes  yes -0.622448
47  1.0  0.0  1.0  1.0  0.0       62.0  yes  yes -1.272989
16  0.0  1.0  0.0  0.0  0.0       24.0   no   no  0.957435
34  0.0  1.0  0.0  0.0  0.0       48.0   no  yes  1.050370
42  1.0  0.0  1.0  1.0  0.0       58.0   no   no -1.087120
28  0.0  1.0  0.0  0.0  0.0  45.130435  yes   no  0.771567
7   0.0  1.0  0.0  0.0  0.0       15.0   no   no  0.957435
53  1.0  0.0  1.0  0.0  1.0       70.0   no  yes  0.585698
40  1.0  0.0  1.0  1.0  0.0       52.0  yes  yes -0.157777
44  1.0  0.0  1.0  1.0  0.0       60.0  yes  yes -1.272989
46  1.0  0.0  1.0  1.0  0.0       54.0  yes  yes -1.087120
19  1.0  0.0  1.0  0.0  1.0       29.0   no   no  1.050370
56  1.0  0.0  1.0  1.0  0.0       78.0  yes  yes -0.994186
39  1.0  0.0  1.0  1.0  0.0       36.0  yes   no  0.771567
25  0.0  1.0  0.0  0.0  0.0       30.0  yes   no  0.399829
38  1.0  0.0  1.0  1.0  0.0       50.0  yes  yes -0.436580
13  1.0  0.0  1.0  0.0  1.0       18.0   no   no  1.050370
50  1.0  0.0  1.0  1.0  0.0       69.0   no  yes -2.667004
3   1.0  0.0  1.0  0.0  1.0       10.0   no   no  1.422107
17  1.0  0.0  1.0  1.0  0.0       26.0   no   no  1.143304
8   0.0  1.0  0.0  0.0  0.0       18.0   no   no -1.458858
55  1.0  0.0  1.0  1.0  0.0       62.0  yes  yes -1.180055
6   0.0  1.0  0.0  0.0  0.0       13.0   no   no  1.050370
36  1.0  0.0  1.0  1.0  0.0       40.0   no   no  0.957435
64  1.0  0.0  1.0  1.0  0.0       84.0  yes  yes -0.622448
69  1.0  0.0  1.0  1.0  0.0       76.0  yes  yes -0.157777
68  1.0  0.0  1.0  1.0  0.0       81.0  yes  yes -0.622448
15  0.0  1.0  0.0  0.0  0.0       25.0   no   no  1.050370
27  0.0  1.0  0.0  0.0  0.0       32.0   no  yes  0.213961
41  1.0  0.0  1.0  1.0  0.0       56.0  yes  yes -0.436580
26  0.0  1.0  0.0  0.0  0.0       35.0   no   no  0.678632
48  1.0  0.0  1.0  1.0  0.0       63.0  yes  yes -1.458858
24  1.0  0.0  1.0  0.0  1.0       28.0   no   no  0.678632
59  1.0  0.0  1.0  1.0  0.0       56.0  yes   no -0.529514
63  1.0  0.0  1.0  1.0  0.0       90.0  yes  yes -1.365923
11  1.0  0.0  1.0  0.0  1.0       17.0   no   no  1.050370
32  0.0  1.0  0.0  0.0  0.0       40.0   no  yes  0.771567
66  0.0  1.0  0.0  0.0  0.0       61.0   no  yes  0.771567
61  1.0  0.0  1.0  1.0  0.0       82.0  yes  yes -0.808317
37  0.0  1.0  0.0  0.0  0.0       49.0   no   no -0.157777
29  0.0  1.0  0.0  0.0  0.0       32.0   no   no  0.678632
43  1.0  0.0  1.0  1.0  0.0       59.0   no  yes -1.180055
65  1.0  0.0  1.0  1.0  0.0       86.0   no  yes -0.529514
1   1.0  0.0  1.0  0.0  1.0       12.0   no   no  1.422107
52  1.0  0.0  1.0  1.0  0.0       61.0  yes  yes -0.529514
21  1.0  0.0  1.0  0.0  1.0       19.0   no   no  0.678632
2   1.0  0.0  1.0  0.0  1.0       15.0   no   no  1.143304
23  1.0  0.0  1.0  0.0  1.0       26.0   no   no  0.034826
20  0.0  1.0  0.0  0.0  0.0       30.0   no   no -1.830595
60  1.0  0.0  1.0  1.0  0.0       80.0   no  yes  0.957435
14  1.0  0.0  1.0  0.0  1.0       20.0   no   no  0.957435
51  1.0  0.0  1.0  1.0  0.0       64.0  yes  yes -0.808317